
services:

  db:
    build: ./mongodb-rs
    container_name: techdoc_db
    command: ["mongod", "--auth", "--bind_ip_all", "--replSet", "rs0"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
      MONGO_REPLICA_HOST: techdoc_db
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    container_name: techdoc_app
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - python-service
    networks:
      - app-network

  python-service:
    build:
      context: ./backend/python
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    container_name: techdoc_python_service
    ports:
      - "5001:5001"
    networks:
      - app-network
    restart: unless-stopped

  
volumes:
  mongodb_data:

networks:
  app-network:
     driver: bridge
